iPBS: ipbs_boundary.hh File Reference
ipbs_boundary.hh File Reference
Functions
template<class GV , class DGF , typename Mapper >
void ipbs_boundary (const GV &gv, const DGF &udgf, const Mapper &mapper, std::vector< double > &fluxContainer)
Precompute the IPBS boundary flux values.
Function Documentation
template<class GV , class DGF , typename Mapper > void ipbs_boundary (const GV & gv, const DGF & udgf, const Mapper & mapper, std::vector< double > & fluxContainer)
Precompute the IPBS boundary flux values.
Here goes some explanation on what is done :-)
Todo:
{ Doc Me ! }
References SysParams::add_error(), SysParams::counter, eval_elliptic(), SysParams::get_alpha(), SysParams::get_bjerrum(), SysParams::get_charge_density(), SysParams::get_error(), SysParams::get_lambda2i(), SysParams::get_symmetry(), integrateentity(), SysParams::pi, SysParams::reset_error(), and sysParams.
Referenced by ipbs_P1().