iPBS: PBLocalOperator< M, B, J > Class Template Reference
PBLocalOperator< M, B, J > Class Template Reference
#include <src/PBLocalOperator.hh>
Public Types
enum { doPatternVolume = true }
enum { doAlphaVolume = true }
enum { doAlphaBoundary = true }
Public Member Functions
PBLocalOperator (const M &m_, const B &b_, const J &j_, std::vector< double > &fluxContainer_, unsigned int intorder_=2)
template<typename EG , typename LFSU , typename X , typename LFSV , typename R >
void alpha_volume (const EG &eg, const LFSU &lfsu, const X &x, const LFSV &lfsv, R &r) const
template<typename IG , typename LFSU , typename X , typename LFSV , typename R >
void alpha_boundary (const IG &ig, const LFSU &lfsu_s, const X &x_s, const LFSV &lfsv_s, R &r_s) const
template<typename M, typename B, typename J>
class PBLocalOperator< M, B, J >
Member Enumeration Documentation
template<typename M , typename B , typename J > anonymous enum
Enumerator:
doPatternVolume
template<typename M , typename B , typename J > anonymous enum
Enumerator:
doAlphaVolume
template<typename M , typename B , typename J > anonymous enum
Enumerator:
doAlphaBoundary
Constructor & Destructor Documentation
template<typename M , typename B , typename J > PBLocalOperator< M, B, J >::PBLocalOperator (const M & m_, const B & b_, const J & j_, std::vector< double > & fluxContainer_, unsigned int intorder_ = 2) [inline]
Member Function Documentation
template<typename M , typename B , typename J > template<typename IG , typename LFSU , typename X , typename LFSV , typename R > void PBLocalOperator< M, B, J >::alpha_boundary (const IG & ig, const LFSU & lfsu_s, const X & x_s, const LFSV & lfsv_s, R & r_s) const [inline]
References SysParams::get_symmetry(), SysParams::pi, and sysParams.
template<typename M , typename B , typename J > template<typename EG , typename LFSU , typename X , typename LFSV , typename R > void PBLocalOperator< M, B, J >::alpha_volume (const EG & eg, const LFSU & lfsu, const X & x, const LFSV & lfsv, R & r) const [inline]
References SysParams::get_lambda2i(), SysParams::get_symmetry(), SysParams::pi, and sysParams.
The documentation for this class was generated from the following file:
PBLocalOperator.hh