iPBS: RefBoundaryFlux< GV, RF, PGMap > Class Template Reference
RefBoundaryFlux< GV, RF, PGMap > Class Template Reference
#include <src/boundaries.hh>
Public Types
typedef
Dune::PDELab::BoundaryGridFunctionTraits
< GV, RF, 1, Dune::FieldVector
< RF, 1 > > Traits
typedef
Traits::GridViewType::Grid::ctype ctype
Public Member Functions
RefBoundaryFlux (const GV &gv_, const PGMap &pg_)
template<typename I , typename E >
void evaluate (I &i, E &e, typename Traits::RangeType &y) const
template<typename GV, typename RF, typename PGMap>
class RefBoundaryFlux< GV, RF, PGMap >
Member Typedef Documentation
template<typename GV , typename RF , typename PGMap > typedef Traits::GridViewType::Grid::ctype RefBoundaryFlux< GV, RF, PGMap >::ctype
template<typename GV , typename RF , typename PGMap > typedef Dune::PDELab::BoundaryGridFunctionTraits< GV,RF,1,Dune::FieldVector<RF,1> > RefBoundaryFlux< GV, RF, PGMap >::Traits
Constructor & Destructor Documentation
template<typename GV , typename RF , typename PGMap > RefBoundaryFlux< GV, RF, PGMap >::RefBoundaryFlux (const GV & gv_, const PGMap & pg_) [inline]
Member Function Documentation
template<typename GV , typename RF , typename PGMap > template<typename I , typename E > void RefBoundaryFlux< GV, RF, PGMap >::evaluate (I & i, E & e, typename Traits::RangeType & y) const [inline]
References SysParams::get_bjerrum(), SysParams::get_charge_density(), SysParams::get_radius(), SysParams::get_sphere_pos(), and sysParams.
The documentation for this class was generated from the following file:
boundaries.hh