iPBS: iPBS.cc File Reference
iPBS.cc File Reference
IPBS - An Iterative Poisson Boltzmann implementation using DUNE.
Classes
struct Cmdparam
container for commandline arguments
Defines
#define _SYSPARAMS_H
Typedefs
typedef double Real
Functions
int main (int argc, char **argv)
Detailed Description
IPBS - An Iterative Poisson Boltzmann implementation using DUNE.
Here goes some explanation on what is done :-)
Todo:
{ Doc Me ! }
Define Documentation
#define _SYSPARAMS_H
Typedef Documentation
typedef double Real
Function Documentation
int main (int argc, char ** argv)
References Cmdparam::GridName, ipbs_P1(), ref_P1(), Cmdparam::RefinementLevel, SysParams::set_alpha(), and sysParams.