iPBS: SysParams Class Reference
SysParams Class Reference
#include <src/sysparams.hh>
Public Member Functions
SysParams (double _lambda, double _bjerrum, double _charge_density, double _epsilon, double _radius)
double get_bjerrum ()
double get_sphere_pos ()
double get_radius ()
double get_epsilon ()
double get_lambda2i ()
double get_charge_density ()
void add_error (double)
void reset_error ()
double get_error ()
void set_lambda (double value)
double get_alpha ()
void set_alpha (double)
int get_symmetry ()
Public Attributes
int counter
Static Public Attributes
static const double pi = 3.14159265358979323846
Constructor & Destructor Documentation
SysParams::SysParams (double _lambda = 1.0, double _bjerrum = 0.7, double _charge_density = 55, double _epsilon = 80.0, double _radius = 1.0)
Member Function Documentation
void SysParams::add_error (double error)
Referenced by ipbs_boundary().
double SysParams::get_alpha ()
Referenced by ipbs_boundary().
double SysParams::get_bjerrum ()
Referenced by RefBoundaryFlux< GV, RF, PGMap >::evaluate(), and ipbs_boundary().
double SysParams::get_charge_density ()
Referenced by RefBoundaryFlux< GV, RF, PGMap >::evaluate(), and ipbs_boundary().
double SysParams::get_epsilon ()
double SysParams::get_error ()
Referenced by ipbs_boundary(), and ipbs_P1().
double SysParams::get_lambda2i ()
Referenced by RefLocalOperator< M, B, J >::alpha_volume(), PBLocalOperator< M, B, J >::alpha_volume(), and ipbs_boundary().
double SysParams::get_radius ()
Referenced by RefBoundaryFlux< GV, RF, PGMap >::evaluate(), and BoundaryFlux< GV, RF, PGMap >::evaluate().
double SysParams::get_sphere_pos ()
Referenced by RefBoundaryFlux< GV, RF, PGMap >::evaluate(), and BoundaryFlux< GV, RF, PGMap >::evaluate().
int SysParams::get_symmetry ()
Referenced by RefLocalOperator< M, B, J >::alpha_boundary(), PBLocalOperator< M, B, J >::alpha_boundary(), RefLocalOperator< M, B, J >::alpha_volume(), PBLocalOperator< M, B, J >::alpha_volume(), and ipbs_boundary().
void SysParams::reset_error ()
Referenced by ipbs_boundary().
void SysParams::set_alpha (double alpha_in)
Referenced by main().
void SysParams::set_lambda (double value)
Member Data Documentation
int SysParams::counter
Referenced by ipbs_boundary(), and ipbs_P1().
const double SysParams::pi = 3.14159265358979323846 [static]
Referenced by RefLocalOperator< M, B, J >::alpha_boundary(), PBLocalOperator< M, B, J >::alpha_boundary(), RefLocalOperator< M, B, J >::alpha_volume(), PBLocalOperator< M, B, J >::alpha_volume(), and ipbs_boundary().
The documentation for this class was generated from the following files:
sysparams.hh
sysparams.cc